# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/sm8650-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pdx245,$(TARGET_DEVICE)),)

endif
